package com.cassens.autotran.activities;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.TextView;

import com.cassens.autotran.CommonUtility;
import com.cassens.autotran.Logs;
import com.cassens.autotran.R;
import com.cassens.autotran.data.local.DataManager;
import com.cassens.autotran.data.remote.tasks.ConsolidatedDataPullTask;
import com.cassens.autotran.data.remote.tasks.DiagnosticTestsTask;
import com.cassens.autotran.data.remote.tasks.PingTestsTask;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CommunicationsActivity extends ProgressDialogActivity implements OnClickListener {
	protected static final Logger log = LoggerFactory.getLogger(CommunicationsActivity.class.getSimpleName());
	String driverNumber = "";


	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_communications);
		findViewById(R.id.img_back).setOnClickListener(this);
		findViewById(R.id.ping_tests_button).setOnClickListener(this);
		findViewById(R.id.refresh_lookup_codes_button).setOnClickListener(this);
		findViewById(R.id.download_tests_button).setOnClickListener(this);
		findViewById(R.id.get_driver_actions_button).setOnClickListener(this);
		findViewById(R.id.view_messages_button).setOnClickListener(this);
		findViewById(R.id.problemReport).setOnClickListener(this);

		driverNumber = getIntent().getStringExtra("driverNumber");
		TextView contactInfo = findViewById(R.id.support_contact_tv);
		CommonUtility.appendEpodContactInfo(this, contactInfo,
				DataManager.getUserForDriverNumber(this, driverNumber));
	}

	ConsolidatedDataPullTask.IConsolidatedDataPullCallback callback = new ConsolidatedDataPullTask.IConsolidatedDataPullCallback() {
		@Override
		public void updateProgress(String status) {
			updateStatus(status);
		}

		@Override
		public void complete() {
			dismissDialog();
		}
	};

	@Override
	public void onClick(View v) {
		int id = v.getId();
		if (id == R.id.img_back) {
			//CommonUtility.logButtonClick(log, "Back");
			this.finish();
			return;
		}
		CommonUtility.logButtonClick(log, v);
		if (id == R.id.ping_tests_button) {
			new PingTestsTask(this).execute();
		} else if (id == R.id.refresh_lookup_codes_button) {
				CommonUtility.showText("Refreshing Lookup Codes");
                //insertDemoShuttleMoves();
                showProgressDialog("Refreshing lookup codes");

                DataManager.refreshLookupCodes(this, true, callback);
		} else if(id == R.id.download_tests_button) {
			new DiagnosticTestsTask(this).execute();
		} else if(id == R.id.get_driver_actions_button) {
			showProgressDialog("Refreshing driver actions");
			// Just pull incremental changes from all lookup tables, which includes driver actions.
			DataManager.refreshLookupCodes(this, false, callback);
		} else if(id == R.id.view_messages_button){
			startActivity(new Intent(this, ViewMessagesActivity.class));
		} else if(id == R.id.problemReport){
			startActivity(new Intent(this, ProblemReportActivity.class));
		}
	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
//		if (resultCode == 11)
//		{
//			((EditText) findViewById(R.id.et_notes_message)).setText(data.getStringExtra("note"));
//		}
		super.onActivityResult(requestCode, resultCode, data);
	}

	public void insertDemoShuttleMoves() {
		CommonUtility.showText("Inserting demo shuttle moves");
		  DataManager.insertShuttleMove(this, "44CE NNCASSENS CONNERS YARD     KNAPHEIDE TRUCK EQUIPMENTCLN**");
		  DataManager.insertShuttleMove(this, "44OD NNLIME-MAG-OLIVE-PEACH LOTSVLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "4429 NNLIME-MAG-OLIVE-PEACH LOTSJEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44AB NNDETROIT METRO AIRPORT    VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50PB NNDETROIT METRO AIRPORT    VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50UC NLDETROIT METRO AIRPORT    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44D4 NNDETROIT METRO AIRPORT    DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "50RU NNDETROIT METRO AIRPORT    CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "44AH NNDETROIT METRO AIRPORT    VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44B5 NYDETROIT METRO AIRPORT    JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "50TL NYDETROIT METRO AIRPORT    OTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "50N1 NYDETROIT METRO AIRPORT    ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "50AS NNDETROIT METRO AIRPORT    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57NU NNARGUS REDFORD            STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50EO NNARGUS REDFORD            PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "57WR NNARGUS REDFORD            VLS WOODHAVEN STORAGE YARCLN**");
		  DataManager.insertShuttleMove(this, "50PA NYARGUS REDFORD            ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "50GH NYARGUS REDFORD            VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "50RR NYARGUS REDFORD            DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "44AD NNDETROIT AXLE YD - VASCOR CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44AR NLDETROIT AXLE YD - VASCOR CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50XG NNDETROIT AXLE YD - VASCOR GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "50AI NNDETROIT AXLE YD - VASCOR CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "57TX NNDETROIT AXLE YD - VASCOR CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "44AS NNDETROIT AXLE YD - VASCOR CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44AS NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44AS NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "50AN NNDETROIT AXLE YD - VASCOR OTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44BF NNVLS BUDD YARD            KNAPHEIDE TRUCK EQUIPMENTCLN**");
		  DataManager.insertShuttleMove(this, "44BG NNVLS BUDD YARD            GROUND EFFECTS LTD       CLN**");
		  DataManager.insertShuttleMove(this, "44BN NNVLS BUDD YARD            NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "50BP NNVLS BUDD YARD            PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "50BJ NLVLS BUDD YARD            CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50BD NNVLS BUDD YARD            DANA TEST FACILITY       CLN**");
		  DataManager.insertShuttleMove(this, "50XM NNVLS BUDD YARD            CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "44MH NNVLS BUDD YARD            NBC TRUCKING EQUIPMENT   CLN**");
		  DataManager.insertShuttleMove(this, "44BV NNVLS BUDD YARD            SUPREME NITRO            CLN**");
		  DataManager.insertShuttleMove(this, "44TQ NNVLS BUDD YARD            CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44TQ NNVLS BUDD YARD            CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44TQ NNVLS BUDD YARD            CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "44BW NNVLS BUDD YARD            VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "50DU NYVLS BUDD YARD            ARGUS REDFORD            CLN**");
		  DataManager.insertShuttleMove(this, "44CB NNCANFIELD EQUIPMENT SERVICVLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44NM NLCANFIELD EQUIPMENT SERVICCASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44SE NNCANFIELD EQUIPMENT SERVICDANA TEST FACILITY       CLN**");
		  DataManager.insertShuttleMove(this, "44CD NNCANFIELD EQUIPMENT SERVICDODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44HC NNCANFIELD EQUIPMENT SERVICFLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "44CH NNCANFIELD EQUIPMENT SERVICVASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44F3 NNCANFIELD EQUIPMENT SERVICJEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44CI NNCANFIELD EQUIPMENT SERVICDETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "44CM NNCANFIELD EQUIPMENT SERVICMAPLE LANE STG YARD-VASC CLN**");
		  DataManager.insertShuttleMove(this, "44CA NNCANFIELD EQUIPMENT SERVICMOORE NITRO CREEK        CLN**");
		  DataManager.insertShuttleMove(this, "44E3 NNCANFIELD EQUIPMENT SERVICNEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44CT NNCANFIELD EQUIPMENT SERVICOTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44CS NNCANFIELD EQUIPMENT SERVICCASSENS TRANSPORT SHAP   CLN**");
		  DataManager.insertShuttleMove(this, "44H2 NNCANFIELD EQUIPMENT SERVICCASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44H2 NNCANFIELD EQUIPMENT SERVICCASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44H2 NNCANFIELD EQUIPMENT SERVICCASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "44DT NNCANFIELD EQUIPMENT SERVICTAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44CW NNCANFIELD EQUIPMENT SERVICVLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "57CS NNVLS BUDD YARD            STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "44ED NNCN RAIL YARD             JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44CJ NNCN RAIL YARD             VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50CJ NYDETROIT                  VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "4430 NNDODGE CITY               LIME-MAG-OLIVE-PEACH LOTSCLN**");
		  DataManager.insertShuttleMove(this, "44DB NNDODGE CITY               VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44Y6 NNDODGE CITY               VLS BUDD YARD STORAGE    CLN**");
		  DataManager.insertShuttleMove(this, "44A8 NNDODGE CITY               CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44HH NNDODGE CITY               VASCOR HUBER YARD STORAGECLN**");
		  DataManager.insertShuttleMove(this, "44DJ NNDODGE CITY               JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44D1 NNDODGE CITY               NBC TRUCKING EQUIPMENT   CLN**");
		  DataManager.insertShuttleMove(this, "44UR NNDODGE CITY               UNITED ROAD YARD         CLN**");
		  DataManager.insertShuttleMove(this, "44WH NNDODGE CITY               VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "44YY NNDODGE CITY               YOST RD YARD - VASCOR    CLN**");
		  DataManager.insertShuttleMove(this, "44FC NNDETROIT AXLE YD - VASCOR NBC TRUCKING EQUIPMENT   CLN**");
		  DataManager.insertShuttleMove(this, "57MS NNDETROIT AXLE YD - VASCOR STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57SA NNSTERLING HEIGHTS         DETROIT AXLE YD - VASCOR CLN**");
		  DataManager.insertShuttleMove(this, "57XS NNDETROIT AXLE YD - VASCOR STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57SK NNSTERLING HEIGHTS         VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "50LC NLDETROIT AXLE YD - VASCOR CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50XL NNDETROIT AXLE YD - VASCOR PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44EU NNJEFFERSON RAIL           UNITED ROAD YARD         CLN**");
		  DataManager.insertShuttleMove(this, "44EJ NNFLAT ROCK AUTO AUCTION   JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "50DB NNDODGE CITY PLANT         VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "57OW NNDODGE CITY CH            VLS WOODHAVEN STORAGE YARCLN**");
		  DataManager.insertShuttleMove(this, "50DI NNDODGE CITY PLANT         CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "50DP NNDODGE CITY PLANT         PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44JR NNDODGE CITY               DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "44JE NLDODGE CITY               CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44I8 NNDODGE CITY               TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "50EJ NLDETROIT                  CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50FR FNFLAT ROCK RAMP 5P (FROCK)NS RAIL - MELVINDALE 58  CLN**");
		  DataManager.insertShuttleMove(this, "57KU NNSTERLING HEIGHTS         FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "57UK NNFLAT ROCK AUTO AUCTION   STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57FT NNFLAT ROCK AUTO AUCTION   TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "57FW NNFLAT ROCK AUTO AUCTION   VLS WEST ROAD YARD       CLN**");
		  DataManager.insertShuttleMove(this, "44PP NNFLAT ROCK AUTO AUCTION   VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50FN NLFLAT ROCK AUTO AUCTION   CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50FM NNFLAT ROCK AUTO AUCTION   CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "50FP NNFLAT ROCK AUTO AUCTION   PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44FB NNKNAPHEIDE TRUCK EQUIPMENTVASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44SS NLKNAPHEIDE TRUCK EQUIPMENTCASSENS JEFFERSON YARD   JLY**");
		  DataManager.insertShuttleMove(this, "44FW NNKNAPHEIDE TRUCK EQUIPMENTVLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "44GN NNGROUND EFFECTS LTD       NORTHLINE STORAGE YARD   CLN**");
		  DataManager.insertShuttleMove(this, "44GC NNGROUND EFFECTS LTD       DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "44XB NNGROUND EFFECTS LTD       VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44GG NLGROUND EFFECTS LTD       CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44GF NNGROUND EFFECTS LTD       FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "44HJ NNGROUND EFFECTS LTD       VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44GJ NNGROUND EFFECTS LTD       JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44GE NNGROUND EFFECTS LTD       CN RAIL YARD             CLN**");
		  DataManager.insertShuttleMove(this, "44GM NNGROUND EFFECTS LTD       MAPLE LANE STG YARD-VASC CLN**");
		  DataManager.insertShuttleMove(this, "44GK NNGROUND EFFECTS LTD       MAPLE LANE STG YARD-VASC CLN**");
		  DataManager.insertShuttleMove(this, "44XS NNGROUND EFFECTS LTD       CASSENS TRANSPORT SHAP   CLN**");
		  DataManager.insertShuttleMove(this, "44K1 NNGROUND EFFECTS LTD       TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44XU NNGROUND EFFECTS LTD       UNITED ROAD YARD         CLN**");
		  DataManager.insertShuttleMove(this, "44GW NNGROUND EFFECTS LTD       VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "44GR NNGROUND EFFECTS LTD       YOST RD YARD - VASCOR    CLN**");
		  DataManager.insertShuttleMove(this, "4428 NNGROUND EFFECTS LTD       LIME-MAG-OLIVE-PEACH LOTSCLN**");
		  DataManager.insertShuttleMove(this, "44HB NNVASCOR HUBER YARD        VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44HF NLVASCOR HUBER YARD        CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44FA NNVASCOR HUBER YARD        DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44JH NNVASCOR HUBER YARD        JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44CN NNVASCOR HUBER YARD        NBC TRUCKING EQUIPMENT   CLN**");
		  DataManager.insertShuttleMove(this, "44JC NLDETROIT METRO AIRPORT    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50SB NYDETROIT                  VLS BUDD YARD STORAGE    CLN**");
		  DataManager.insertShuttleMove(this, "50DX NYDETROIT                  DETROIT AXLE YD - VASCOR CLN**");
		  DataManager.insertShuttleMove(this, "50DN NNDETROIT                  DANA TEST FACILITY       CLN**");
		  DataManager.insertShuttleMove(this, "50HB NNDETROIT                  VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44JB NNCASSENS CONNER YARD      NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44II NNCASSENS CONNER YARD      CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44II NNCASSENS CONNER YARD      CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44II NNCASSENS CONNER YARD      CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "44JT NNJEFFERSON RAIL           TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "50NU NNDETROIT                  UNITED ROAD YARD         CLN**");
		  DataManager.insertShuttleMove(this, "50GA NNDETROIT                  GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "44JF NNCASSENS CONNER YARD      CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44JF NNCASSENS CONNER YARD      CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44JF NNCASSENS CONNER YARD      CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "50FY NNDETROIT                  YOST RD YARD - VASCOR    CLN**");
		  DataManager.insertShuttleMove(this, "50FW NNDETROIT                  CN STORAGE YARD          CLN**");
		  DataManager.insertShuttleMove(this, "50NQ NNDETROIT                  NORTHLINE STORAGE YARD   CLN**");
		  DataManager.insertShuttleMove(this, "36ME FNFORD KANSAS CITY ASSEMBLYMETRO NORTH MALL         CLN**");
		  DataManager.insertShuttleMove(this, "36MC FNFORD KANSAS CITY ASSEMBLYNS VOLTZ YARD            CLN**");
		  DataManager.insertShuttleMove(this, "36CM FNFORD KANSAS CITY ASSEMBLYMUNCIE RAILHEAD          CLN**");
		  DataManager.insertShuttleMove(this, "36RG FNFORD KANSAS CITY ASSEMBLYKCS - RICHARDS-GEBAUR    CLN**");
		  DataManager.insertShuttleMove(this, "36VP FNFORD KANSAS CITY ASSEMBLYVehicle Personallization CLN**");
		  DataManager.insertShuttleMove(this, "44KW NNCN RAIL YARD             DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "50KG NNCN STORAGE YARD          GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "50KC NLCN STORAGE YARD          CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44FD NNKNAPHEIDE TRUCK EQUIPMENTDODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44KF NNKNAPHEIDE TRUCK EQUIPMENTFLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "44FJ NYKNAPHEIDE TRUCK EQUIPMENTJEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44FN NNKNAPHEIDE TRUCK EQUIPMENTNEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44KU NNKNAPHEIDE TRUCK EQUIPMENTUNITED ROAD YARD         CLN**");
		  DataManager.insertShuttleMove(this, "44FE NNKNAPHEIDE TRUCK EQUIPMENTVLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44KC NLKNAPHEIDE TRUCK EQUIPMENTCASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44BB NNLEGETT AND PLATT         VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44FG NNDETROIT AXLE YD - VASCOR DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44AF NNDETROIT AXLE YD - VASCOR KNAPHEIDE TRUCK EQUIPMENTCLN**");
		  DataManager.insertShuttleMove(this, "44AG NNDETROIT AXLE YD - VASCOR JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44MG NNMAPLE LANE STG YARD-VASC GROUND EFFECTS LTD       CLN**");
		  DataManager.insertShuttleMove(this, "44MI NLMAPLE LANE STG YARD-VASC CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44AA NNMAPLE LANE STG YARD-VASC DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44MJ NNMAPLE LANE STG YARD-VASC JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44LL NNLEGETT AND PLATT         YOST RD YARD - VASCOR    CLN**");
		  DataManager.insertShuttleMove(this, "44RC NLLEGETT AND PLATT         CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44HD NNLEGETT AND PLATT         MANHEIM                  CLN**");
		  DataManager.insertShuttleMove(this, "44MU NNLEGETT AND PLATT         FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "44MW NNLEGETT AND PLATT         TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44RK NNLEGETT AND PLATT         LIME-MAG-OLIVE-PEACH LOTSCLN**");
		  DataManager.insertShuttleMove(this, "50MJ NLNS RAIL - MELVINDALE     CASSENS JEFFERSON YARD   JLY**");
		  DataManager.insertShuttleMove(this, "50MO NYNS RAIL - MELVINDALE     ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "57EA NNNS RAIL - MELVINDALE     STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "36MV FNMETRO NORTH MALL         NS VOLTZ YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44KG NNMONROE TRUCK EQUIPMENT   JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "50UA NNMOUND RD STORAGE YARD    CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "57OT NNMOUND RD STORAGE YARD    TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "57AN NNMOUND RD STORAGE YARD    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "44B4 NNMOUND RD STORAGE YARD    VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44H7 NNMOUND RD STORAGE YARD    CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44MC NLMOUND RD STORAGE YARD    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50LK NLMOUND RD STORAGE YARD    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50MY NNMOUND RD STORAGE YARD    GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "44B2 NYMOUND RD STORAGE YARD    JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "57IM NNMOUND RD STORAGE YARD    CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "44C4 NNMOUND RD STORAGE YARD    NBC TRUCKING EQUIPMENT   CLN**");
		  DataManager.insertShuttleMove(this, "50RD NYMOUND RD STORAGE YARD    PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "50MH NNMOUND RD STORAGE YARD    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "44LP NNLEGETT AND PLATT         VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44I5 NNLEGETT AND PLATT         DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44I3 NYLEGETT AND PLATT         JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44H4 NNLEGETT AND PLATT         NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44LT NNLEGETT AND PLATT         CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44LT NNLEGETT AND PLATT         CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44LT NNLEGETT AND PLATT         CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "44H3 NNLEGETT AND PLATT         VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "50FA NYDETROIT                  ARGUS REDFORD            CLN**");
		  DataManager.insertShuttleMove(this, "50AU NNDETROIT                  CHRYSLER TECH CENTER     CLN**");
		  DataManager.insertShuttleMove(this, "50JF NYDETROIT                  FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "50JB NNDETROIT                  DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "50NM NYDETROIT                  MOUND RD STORAGE YARD    CLN**");
		  DataManager.insertShuttleMove(this, "50JP NNDETROIT                  PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "50JR NYDETROIT                  ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "50SH NLDETROIT                  CASSENS STERLING HEIGHTS SHY**");
		  DataManager.insertShuttleMove(this, "50SL NNDETROIT                  STERLING HTS RAIL        CLN**");
		  DataManager.insertShuttleMove(this, "50JV NNDETROIT                  STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50JK NYDETROIT                  TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "50NR NYDETROIT                  ROMULUS YARD (TRANSLOGIC)CLN**");
		  DataManager.insertShuttleMove(this, "50JW NYDETROIT                  VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "50FO NYDETROIT                  OTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "57DH NNVLS BUDD YARD            HILL AVENUE YARD         CLN**");
		  DataManager.insertShuttleMove(this, "44BT NNNEW BOSTON RAILHEAD      TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44NB NNNBC TRUCKING EQUIPMENT   VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44NC NLNBC TRUCKING EQUIPMENT   CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44NE NLNBC TRUCKING EQUIPMENT   CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44RD NNNBC TRUCKING EQUIPMENT   DANA TEST FACILITY       CLN**");
		  DataManager.insertShuttleMove(this, "44ND NNNBC TRUCKING EQUIPMENT   DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44NF NNNBC TRUCKING EQUIPMENT   FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "44NH NNNBC TRUCKING EQUIPMENT   VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44G7 NYNBC TRUCKING EQUIPMENT   JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44SF NNNBC TRUCKING EQUIPMENT   MOUND RD STORAGE YARD    CLN**");
		  DataManager.insertShuttleMove(this, "44E7 NNNBC TRUCKING EQUIPMENT   NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44NO NNNBC TRUCKING EQUIPMENT   MOORE NITRO CREEK        CLN**");
		  DataManager.insertShuttleMove(this, "44D7 NNNBC TRUCKING EQUIPMENT   CASSENS TRANSPORT SHAP   CLN**");
		  DataManager.insertShuttleMove(this, "44I4 NNNBC TRUCKING EQUIPMENT   CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44I4 NNNBC TRUCKING EQUIPMENT   CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44I4 NNNBC TRUCKING EQUIPMENT   CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "50OA NNNEW BOSTON RAILHEAD      ROUSH INDUSTRY BLDG #70  CLN**");
		  DataManager.insertShuttleMove(this, "50NJ NLNEW BOSTON RAILHEAD      CASSENS JEFFERSON YARD   JLY**");
		  DataManager.insertShuttleMove(this, "50NA NNNEW BOSTON RAILHEAD      ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "50NL NNNEW BOSTON RAILHEAD      ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "44BD NNNEW BOSTON RAILHEAD      DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44BM NNNEW BOSTON RAILHEAD      LEGETT AND PLATT         CLN**");
		  DataManager.insertShuttleMove(this, "57N4 NYNEW BOSTON RAILHEAD      TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44KB NNNORTHLINE STORAGE YARD   VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50OI NLNORTHLINE STORAGE YARD   CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44NJ NNNORTHLINE STORAGE YARD   JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "50NH NNNORTHLINE STORAGE YARD   CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "44QB NNLIME-MAG-OLIVE-PEACH LOTSVLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50E8 NNDETROIT METRO AIRPORT    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "36RV FNKCS - RICHARDS-GEBAUR    NS VOLTZ YARD            CLN**");
		  DataManager.insertShuttleMove(this, "57PB NNDETROIT METRO AIRPORT    VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "578S NNDETROIT METRO AIRPORT    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57KM NNCN STORAGE YARD          CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "50OF NNDETROIT METRO AIRPORT    PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "50HS NNROUSH INDUSTRY BLDG #70  STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50LA NNROUSH IND - LIVONIA      DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "50RJ NLROUSH IND - LIVONIA      CASSENS JEFFERSON YARD   JLY**");
		  DataManager.insertShuttleMove(this, "50AW NYROUSH IND - LIVONIA      VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "50SA NYCASSENS TRANSPORT SHAP   ARGUS REDFORD            CLN**");
		  DataManager.insertShuttleMove(this, "44SG NNCASSENS TRANSPORT SHAP   CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "57SC NNSTERLING HEIGHTS         VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "57SM NLSTERLING HEIGHTS         CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "57SD NLSTERLING HEIGHTS         CASSENS ELDON YARD       ELY**");
		  DataManager.insertShuttleMove(this, "578R NNSTERLING HEIGHTS         DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "57SL NNSTERLING HEIGHTS         DETROIT AXLE YD - VASCOR CLN**");
		  DataManager.insertShuttleMove(this, "57NA NNSTERLING HEIGHTS         MOUND RD STORAGE YARD    CLN**");
		  DataManager.insertShuttleMove(this, "44XN NNCASSENS TRANSPORT SHAP   NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "44SI NNCASSENS TRANSPORT SHAP   SUPREME NITRO            CLN**");
		  DataManager.insertShuttleMove(this, "57SX NNSTERLING HEIGHTS         PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44SJ NNCASSENS TRANSPORT SHAP   CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44SJ NNCASSENS TRANSPORT SHAP   CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44SJ NNCASSENS TRANSPORT SHAP   CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "57ST NNSTERLING HEIGHTS         TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "50SY NNCASSENS TRANSPORT SHAP   TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44ST NNCASSENS TRANSPORT SHAP   TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "57WS NNSTERLING HEIGHTS         VLS WOODHAVEN STORAGE YARCLN**");
		  DataManager.insertShuttleMove(this, "5714 NNSTERLING HEIGHTS         MAPLE LANE STG YARD-VASC CLN**");
		  DataManager.insertShuttleMove(this, "50SI NYCASSENS TRANSPORT SHAP   DETROIT METRO AIRPORT    CLN**");
		  DataManager.insertShuttleMove(this, "50VT NNCASSENS TRANSPORT SHAP   MOUND RD STORAGE YARD    CLN**");
		  DataManager.insertShuttleMove(this, "50OD NNCASSENS TRANSPORT SHAP   VLS WOODHAVEN STG        CLN**");
		  DataManager.insertShuttleMove(this, "57CC NNCASSENS CONNERS YARD     STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "57S1 NLSTERLING HEIGHTS         CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "57SH NNSTERLING HEIGHTS         HILL AVENUE YARD         CLN**");
		  DataManager.insertShuttleMove(this, "57GA NNSTERLING HEIGHTS         GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "5757 NNSTERLING HEIGHTS         CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "57WE NNSTERLING HEIGHTS         VLS WEST ROAD YARD       CLN**");
		  DataManager.insertShuttleMove(this, "44SC NNCASSENS STICKNEY         CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44SC NNCASSENS TRANSPORT CO.    CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44SC NNCASSENS TRANSPORT COMPANYCANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "57DS NNSTERLING HTS STORAGE YARDDETROIT AXLE YD - VASCOR CLN**");
		  DataManager.insertShuttleMove(this, "50OY NNTAYLOR STG/MANNHEIM AUTO OTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44C9 NLTAYLOR STG/MANNHEIM AUTO CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50TB NLTAYLOR STG/MANNHEIM AUTO CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44J1 NNTAYLOR STG/MANNHEIM AUTO DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "50OM NNTAYLOR STG/MANNHEIM AUTO CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "44TG NNTAYLOR STG/MANNHEIM AUTO GROUND EFFECTS LTD       CLN**");
		  DataManager.insertShuttleMove(this, "57HI NYTAYLOR STG/MANNHEIM AUTO HILL AVENUE YARD         CLN**");
		  DataManager.insertShuttleMove(this, "57TM NNTAYLOR STG/MANNHEIM AUTO CASSENS - Matzinger      MLY**");
		  DataManager.insertShuttleMove(this, "44TB NNTAYLOR STG/MANNHEIM AUTO NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "50TP NNTAYLOR STG/MANNHEIM AUTO PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44YS NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT SHAP   CLN**");
		  DataManager.insertShuttleMove(this, "50TA NNTAYLOR STG/MANNHEIM AUTO STERLING HTS RAIL        CLN**");
		  DataManager.insertShuttleMove(this, "50YS NNTAYLOR STG/MANNHEIM AUTO STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50TH NNTAYLOR STG/MANNHEIM AUTO STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "44TS NNTAYLOR STG/MANNHEIM AUTO CASSENS STICKNEY         CLN**");
		  DataManager.insertShuttleMove(this, "44TS NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT CO.    CLN**");
		  DataManager.insertShuttleMove(this, "44TS NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT COMPANYCLN**");
		  DataManager.insertShuttleMove(this, "57DT NNCASSENS CONNER YARD      TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "57SS NNTAYLOR STG/MANNHEIM AUTO STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "5720 NNMAPLE LANE STG YARD-VASC TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "44TJ NNTAYLOR STG/MANNHEIM AUTO JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "44TE NNTAYLOR STG/MANNHEIM AUTO KNAPEHEIDE TRUCK EQUIPMENCLN**");
		  DataManager.insertShuttleMove(this, "57NL NNCASSENS CONNER YARD      NORTHLINE STORAGE YARD   CLN**");
		  DataManager.insertShuttleMove(this, "36VC FNVehicle Personallization FORD KANSAS CITY ASSEMBLYCLN**");
		  DataManager.insertShuttleMove(this, "36VV FNVehicle Personallization NS VOLTZ YARD            CLN**");
		  DataManager.insertShuttleMove(this, "57AR NNDETROIT AXLE YD - VASCOR VLS WEST ROAD YARD       CLN**");
		  DataManager.insertShuttleMove(this, "576W NNDODGE CITY CH            TAYLOR STG/MANNHEIM AUTO CLN**");
		  DataManager.insertShuttleMove(this, "57HW NNSTERLING HEIGHTS         DODGE CITY PLANT         CLN**");
		  DataManager.insertShuttleMove(this, "44WG NNVLS WOODHAVEN STG        GROUND EFFECTS LTD       CLN**");
		  DataManager.insertShuttleMove(this, "44WE NNVLS WOODHAVEN STG        VASCOR HUBER YARD        CLN**");
		  DataManager.insertShuttleMove(this, "44UB NNVLS WOODHAVEN STG        CANFIELD EQUIPMENT SERVICCLN**");
		  DataManager.insertShuttleMove(this, "44HN NNVLS WOODHAVEN STG        NEW BOSTON RAILHEAD      CLN**");
		  DataManager.insertShuttleMove(this, "503I NLWINDSOR                  CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50WF NYWINDSOR                  FLAT ROCK AUTO AUCTION   CLN**");
		  DataManager.insertShuttleMove(this, "50WD NYWINDSOR                  MOUND RD STORAGE YARD    CLN**");
		  DataManager.insertShuttleMove(this, "5035 NLWINDSOR                  CASSENS JEFFERSON YARD   JLY**");
		  DataManager.insertShuttleMove(this, "57WA NNVLS WOODHAVEN STORAGE YARSTERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "5722 NNCN STORAGE YARD          STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50WP NNVLS WOODHAVEN STG        PILLETTE STORAGE FACILITYCLN**");
		  DataManager.insertShuttleMove(this, "44WB NNVLS WOODHAVEN STG        VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "44WQ NNVLS WOODHAVEN STG        VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50WJ NLVLS WOODHAVEN STG        CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44F4 NNVLS WOODHAVEN STG        DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "44B7 NYVLS WOODHAVEN STG        JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "50OT NNVLS WOODHAVEN STG        OTTAWA SOUTH YARD        CLN**");
		  DataManager.insertShuttleMove(this, "57WC NLVLS WOODHAVEN STORAGE YARCASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "57WB NNVLS WOODHAVEN STORAGE YARVLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50WS NNVLS WOODHAVEN STG        STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "50WA NYVLS WOODHAVEN STG        ARGUS REDFORD            CLN**");
		  DataManager.insertShuttleMove(this, "50OG NNVLS WOODHAVEN STG        CASSENS MARAIS YARD      CLN**");
		  DataManager.insertShuttleMove(this, "50WL NYVLS WOODHAVEN STG        ROUSH IND - LIVONIA      CLN**");
		  DataManager.insertShuttleMove(this, "50WH NNVLS WOODHAVEN STG        STERLING HTS RAIL        CLN**");
		  DataManager.insertShuttleMove(this, "44YB NNYOST RD YARD - VASCOR    VLS BUDD YARD            CLN**");
		  DataManager.insertShuttleMove(this, "50YC NLYOST RD YARD - VASCOR    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "44YC NLYOST RD YARD - VASCOR    CASSENS CONNERS YARD     CLY**");
		  DataManager.insertShuttleMove(this, "50YG NNYOST RD YARD - VASCOR    GATEWAY YARD             CLN**");
		  DataManager.insertShuttleMove(this, "44YX NNYOST RD YARD - VASCOR    GROUND EFFECTS LTD       CLN**");
		  DataManager.insertShuttleMove(this, "44YJ NNYOST RD YARD - VASCOR    JEFFERSON RAIL           CLN**");
		  DataManager.insertShuttleMove(this, "57YS NNYOST RD YARD - VASCOR    STERLING HTS STORAGE YARDCLN**");
		  DataManager.insertShuttleMove(this, "44YW NNYOST RD YARD - VASCOR    DODGE CITY               CLN**");
		  DataManager.insertShuttleMove(this, "57SV NNSTERLING HEIGHTS         NS RAIL - MELVINDALE     CLN   19   25   28   30   32   34   38   41   44   47   56   64   72   75   76   AG   BS   BV   CN   CR   DM   DO   GT   HN   HT   KY   LA   LC   M1   M2   M4   M5   M9   MT   PA   SR   SV   VC**");
		  DataManager.insertShuttleMove(this, "50MQ YNMOUND RD STORAGE YARD    NEW BOSTON RAILHEAD      CLN   20   21   23   26   29  29A   49   51   57   58   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AF   AI   AJ   AK   AM  ANT   AO   AR   AT   AY   B2   BA   BE   BH   BO  BPR   BR BRVF BRVX BULF   CA  CAM   CH   CI   CL   CO CROF   D0   DA   DD   DZ   EC   EG   EX   FI   FR   GH   GR HNKF   IL   JO   JX   K3   KW   LB LIVF   LV   MA   ME   NC   NO   NZ   OM   PE   PL   PR PRTF   PT PTBF   PY   QA ROMF   RU   SA   SB   SK   SL SLOF   TA   TH   TR   TW   UE   UJ   UY   VE   VI   VJ WALF   YE   ZA ZEEF   ZZ**");
		  DataManager.insertShuttleMove(this, "50BN NNVLS BUDD YARD            NEW BOSTON RAILHEAD      CLN   20   21   23   26   29  29A   49   51   57   58   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AF   AI   AJ   AK   AM  ANT   AO   AR   AT   AY   B2   BA   BE   BH   BO  BPR   BR BRVF BRVX BULF   CA  CAM   CH   CI   CL   CO CROF   D0   DA   DD   DZ   EC   EG   EX   FI   FR   GH   GR HNKF   IL   JO   JX   K3   KW   LB LIVF   LV   MA   ME   NC   NO   NZ   OM   PE   PL   PR PRTF   PT PTBF   PY   QA ROMF   RU   SA   SB   SK   SL SLOF   TA   TH   TR   TW   UE   UJ   UY   VE   VI   VJ WALF   YE   ZA ZEEF   ZZ**");
		  DataManager.insertShuttleMove(this, "50NB YNDETROIT                  NEW BOSTON RAILHEAD      CLN   20   21   23   26   29  29A   49   51   57   58   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AF   AI   AJ   AK   AM  ANT   AO   AR   AT   AY   B2   BA   BE   BH   BO  BPR   BR BRVF BRVX BULF   CA  CAM   CH   CI   CL   CO CROF   D0   DA   DD   DZ   EC   EG   EX   FI   FR   GH   GR HNKF   IL   JO   JX   K3   KW   LB LIVF   LV   MA   ME   NC   NO   NZ   OM   PE   PL   PR PRTF   PT PTBF   PY   QA ROMF   RU   SA   SB   SK   SL SLOF   TA   TH   TR   TW   UE   UJ   UY   VE   VI   VJ WALF   YE   ZA ZEEF   ZZ**");
		  DataManager.insertShuttleMove(this, "50NW YNCASSENS TRANSPORT SHAP   NEW BOSTON RAILHEAD      CLN   20   21   23   26   29  29A   49   51   57   58   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AF   AI   AJ   AK   AM  ANT   AO   AR   AT   AY   B2   BA   BE   BH   BO  BPR   BR BRVF BRVX BULF   CA  CAM   CH   CI   CL   CO CROF   D0   DA   DD   DZ   EC   EG   EX   FI   FR   GH   GR HNKF   IL   JO   JX   K3   KW   LB LIVF   LV   MA   ME   NC   NO   NZ   OM   PE   PL   PR PRTF   PT PTBF   PY   QA ROMF   RU   SA   SB   SK   SL SLOF   TA   TH   TR   TW   UE   UJ   UY   VE   VI   VJ WALF   YE   ZA ZEEF   ZZ**");
		  DataManager.insertShuttleMove(this, "57CB YNVLS BUDD YARD            NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57DN YNDETROIT AXLE YD - VASCOR NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57FB NNFLAT ROCK AUTO AUCTION   NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57ML NNMAPLE LANE STG YARD-VASC NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "575L YNMOUND RD STORAGE YARD    NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57JB NNCASSENS CONNER YARD      NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57SB YNSTERLING HEIGHTS         NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "574N NNTAYLOR STG/MANNHEIM AUTO NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57WN NNVLS WOODHAVEN STORAGE YARNEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57KW NNCN STORAGE YARD          NEW BOSTON RAILHEAD      CLN   21   23   26   29  29A   49   51   57   60   62   63   66  66A  66L   89   97   AA   AB   AD   AE   AH   AI   AJ   AK   AO   AR   AT   AU   AY   B1   B2   BA   BC   BD   BE   BG   BH   BJ   BO   BR   BU   CA   CE   CH   CI   CJ   CL   CM   CO   CS   CY   CZ   DA   DD   DE   DK   DN   DZ   EA   EC   EG   ES   ET   EX   FA   FB   FI   FR   FX   GA   GB   GH   GR   HK   HU   IL   IN   IR   IS   IT   IX   JO   JP   K3   KR   KW   LB   LR   LS   LV   MA   MG   ML   MY   NA   NC   ND   NE   NG   NL   NO   NX   NZ   OM   PD   PE   PL   PR   PT   PY   QA   RO   RU   SA   SB   SD   SE   SG   SI   SK   SL   SN   SP   SW   SY   TH   TR   TW   UA   UE   UK   UY   VE   VI   VJ   VN   ZA   ZM   ZZ**");
		  DataManager.insertShuttleMove(this, "57SJ YNSTERLING HEIGHTS         JEFFERSON RAIL           CLN   24   27   33   40   45   53   54   58   59   61   65   74   77   87   GU   PI   SX**");
		  DataManager.insertShuttleMove(this, "5788 NNMAPLE LANE STG YARD-VASC JEFFERSON RAIL           CLN   24   27   33   40   45   53   54   58   59   61   65   74   77   87   GU   PI   SX**");
		  DataManager.insertShuttleMove(this, "5799 NNTAYLOR STG/MANNHEIM AUTO JEFFERSON RAIL           CLN   24   27   33   40   45   53   54   58   59   61   65   74   77   87   GU   PI   SX**");
		  DataManager.insertShuttleMove(this, "57KJ NNCN STORAGE YARD          JEFFERSON RAIL           CLN   24   27   33   40   45   53   54   58   59   61   65   74   77   87   GU   PI   SX**");
		  DataManager.insertShuttleMove(this, "50RO NNDETROIT METRO AIRPORT    CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50RO NNDETROIT METRO AIRPORT    CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50RO NNDETROIT METRO AIRPORT    CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50XT NNDETROIT AXLE YD - VASCOR CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50XT NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50XT NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50FT NNFLAT ROCK AUTO AUCTION   CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50FT NNFLAT ROCK AUTO AUCTION   CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50FT NNFLAT ROCK AUTO AUCTION   CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50JO NNDETROIT                  CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50JO NNDETROIT                  CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50JO NNDETROIT                  CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50EE NNCASSENS TRANSPORT SHAP   CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50EE NNCASSENS TRANSPORT SHAP   CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50EE NNCASSENS TRANSPORT SHAP   CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50YT NNTAYLOR STG/MANNHEIM AUTO CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50YT NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50YT NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50HT NNVLS WOODHAVEN STG        CASSENS STICKNEY         CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50HT NNVLS WOODHAVEN STG        CASSENS TRANSPORT CO.    CLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50HT NNVLS WOODHAVEN STG        CASSENS TRANSPORT COMPANYCLN   3A   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57TH NNSTERLING HEIGHTS          NITRO CREEK             CLN   3A   7A   7C   7B   7D   7E   7G   7H   7K   7L   7J   7M   7N**");
		  DataManager.insertShuttleMove(this, "50MV YNMOUND RD STORAGE YARD    NS RAIL - MELVINDALE     CLN   3R   47   BV   MT**");
		  DataManager.insertShuttleMove(this, "50JM YNDETROIT                  NS RAIL - MELVINDALE     CLN   3R   47   BV   MT**");
		  DataManager.insertShuttleMove(this, "44CC NNCANFIELD EQUIPMENT SERVICDETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44Y5 NNDODGE CITY               DETROIT AXLE YD - STORAGECLN  4E2**");
		  DataManager.insertShuttleMove(this, "44DQ NNDODGE CITY               DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44WD NNVLS WOODHAVEN STG        DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44FF NNKNAPHEIDE TRUCK EQUIPMENTDETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44GY NNGROUND EFFECTS LTD       DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44HE NNVASCOR HUBER YARD        DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44KA NNDETROIT METRO AIRPORT    DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44MA NNLEGETT AND PLATT         DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "4435 NNMOUND RD STORAGE YARD    DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "44NN NNNBC TRUCKING EQUIPMENT   DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "4433 NNTAYLOR STG/MANNHEIM AUTO DETROIT AXLE YD - VASCOR CLN  4E2**");
		  DataManager.insertShuttleMove(this, "57XT NNDETROIT AXLE YD - VASCOR CASSENS STICKNEY         CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57XT NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT CO.    CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57XT NNDETROIT AXLE YD - VASCOR CASSENS TRANSPORT COMPANYCLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57FO YNFLAT ROCK AUTO AUCTION   CASSENS STICKNEY         CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57FO YNFLAT ROCK AUTO AUCTION   CASSENS TRANSPORT CO.    CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57FO YNFLAT ROCK AUTO AUCTION   CASSENS TRANSPORT COMPANYCLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57MI NNMOUND RD STORAGE YARD    CASSENS STICKNEY         CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57MI NNMOUND RD STORAGE YARD    CASSENS TRANSPORT CO.    CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57MI NNMOUND RD STORAGE YARD    CASSENS TRANSPORT COMPANYCLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57HT YNSTERLING HEIGHTS         CASSENS STICKNEY         CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57HT YNSTERLING HEIGHTS         CASSENS TRANSPORT CO.    CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57HT YNSTERLING HEIGHTS         CASSENS TRANSPORT COMPANYCLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57TT NNTAYLOR STG/MANNHEIM AUTO CASSENS STICKNEY         CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57TT NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT CO.    CLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "57TT NNTAYLOR STG/MANNHEIM AUTO CASSENS TRANSPORT COMPANYCLN   4H   4J   4L   4M   4P   4R   4T   4W**");
		  DataManager.insertShuttleMove(this, "50U2 YNDETROIT METRO AIRPORT    CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50BW YNVLS BUDD YARD            CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50AX NNDETROIT AXLE YD - VASCOR CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50CW YNDODGE CITY PLANT         CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50FC NNFLAT ROCK AUTO AUCTION   CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50CC YNVASCOR HUBER YARD        CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50RE YNMOUND RD STORAGE YARD    CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "503F YNDETROIT                  CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50NC NNNORTHLINE STORAGE YARD   CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50SW YNCASSENS TRANSPORT SHAP   CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50TC YNTAYLOR STG/MANNHEIM AUTO CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "50WW NNVLS WOODHAVEN STG        CP RAIL FACILITY WEST    CLN   67   A2  A2A   B3   C1   D1   D2  D2A   P1**");
		  DataManager.insertShuttleMove(this, "503B YLDETROIT                  CASSENS CONNERS YARD     CLY   67   A2  A2A   B3   C1   D1   D2  D2A   P1   F9   T1   T3   B1**");
		  DataManager.insertShuttleMove(this, "57OF NNFLAT ROCK AUTO AUCTION   SUPREME NITRO            CLN   7A   7C**");
		  DataManager.insertShuttleMove(this, "57MT NNMOUND RD STORAGE YARD    SUPREME NITRO            CLN   7A   7C**");
		  DataManager.insertShuttleMove(this, "57TN NNTAYLOR STG/MANNHEIM AUTO SUPREME NITRO            CLN   7A   7C**");
		  DataManager.insertShuttleMove(this, "50RN NNDETROIT METRO AIRPORT    FLEETCAR NITRO           CLN   7B   7D   7E   7G   7H**");
		  DataManager.insertShuttleMove(this, "50CT NNVLS BUDD YARD            FLEETCAR NITRO           CLN   7B   7D   7E   7G   7H**");
		  DataManager.insertShuttleMove(this, "50JT NNDETROIT                  FLEETCAR NITRO           CLN   7B   7D   7E   7G   7H**");
		  DataManager.insertShuttleMove(this, "50DE NNCASSENS TRANSPORT SHAP   FLEETCAR NITRO           CLN   7B   7D   7E   7G   7H**");
		  DataManager.insertShuttleMove(this, "57DO NNDODGE CITY CH            AA OTTAWA YARD           CLN   A1   D3   D4**");
		  DataManager.insertShuttleMove(this, "57SO NNSTERLING HEIGHTS         AA OTTAWA YARD           CLN   A1   D3   D4**");
		  DataManager.insertShuttleMove(this, "57SP NNSTERLING HEIGHTS         CP RAIL - EAST           CLN  A2A   E1   H1   L1   S1   W1**");
		  DataManager.insertShuttleMove(this, "50VE NNDETROIT METRO AIRPORT    CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50XE NNDETROIT AXLE YD - VASCOR CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50BE NNVLS BUDD YARD            CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50FE NNDODGE CITY PLANT         CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50UE NNVASCOR HUBER YARD        CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50D1 NNDETROIT                  CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50KE NNCN STORAGE YARD          CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50OR NNMOUND RD STORAGE YARD    CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50TE NNTAYLOR STG/MANNHEIM AUTO CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50VR NNVLS WOODHAVEN STG        CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50YE NNYOST RD YARD - VASCOR    CN-E.C. ROW RAIL YARD    CLN   A8  A9A  D4A**");
		  DataManager.insertShuttleMove(this, "50YW NNYOST RD YARD - VASCOR    CP RAIL - EAST           CLN   B1**");
		  DataManager.insertShuttleMove(this, "50RA NNDETROIT METRO AIRPORT    JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50XJ NNDETROIT AXLE YD - VASCOR JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50DL YNDODGE CITY PLANT         JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50NO NYDETROIT                  JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50GF NNFLAT ROCK AUTO AUCTION   JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50HU NNVASCOR HUBER YARD        JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50KJ NYCN STORAGE YARD          JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50ML NNNS RAIL - MELVINDALE     JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50LJ NNMOUND RD STORAGE YARD    JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50OL NNNORTHLINE STORAGE YARD   JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50RL NNROUSH IND - LIVONIA      JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50SJ NNMICHIGAN STATE FAIRGROUNDJEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50SD NNSTERLING HEIGHTS         JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50TT NNTAYLOR STG/MANNHEIM AUTO JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50HJ NNVLS WOODHAVEN STG        JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "50YJ NNYOST RD YARD - VASCOR    JEFFERSON RAIL           CLN   SG**");
		  DataManager.insertShuttleMove(this, "44BA NNDETROIT AXLE YD - VASCOR BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "44BI NNVLS BUDD YARD            BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "44CF NNCASSENS CONNERS YARD     BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "44DD NNDODGE CITY               BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "44GV NYGROUND EFFECTS LTD       BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "50MB NNMOUND RD STORAGE YARD    BRAMPTON TERMINAL        CLN   T6**");
		  DataManager.insertShuttleMove(this, "44MB NNMOUND RD STORAGE YARD    BRAMPTON TERMINAL        CLN   T6**");
		CommonUtility.showText("Inserted demo shuttle moves");
	  }

}
